# Generated by Django 5.2.4 on 2025-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service', # table iss name s bnegi 
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
                ('service_icon', models.DateField(max_length=50)),
            ],
        ),
    ]
